language: node_js
node_js:
- "0.10"
- "0.11"
- "0.12"
- "iojs"
before_install: 
- gem install bundler
- npm install -g grunt-cli
install: npm install
script: npm test
after_script: npm run codeclimate
